version: '3.7'

services:
  app:
    image: localhost:5000/fbmapapi:v1
    ports: 
    - "5005:5005"
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000 || exit 1"]
      interval: 90ms
      timeout: 10s
      retries: 3
      start_period: 40s